# Generated by Django 5.0.4 on 2024-04-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0004_carlist_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cardekho_app.showroomlist'),
        ),
    ]
