# Generated by Django 5.0.4 on 2024-05-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cardekho_app.showroomlist'),
        ),
    ]
