# Generated by Django 5.0.4 on 2024-05-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0007_alter_carlist_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews1', to='cardekho_app.showroomlist'),
        ),
    ]
