# Generated by Django 5.0.4 on 2024-05-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0008_review_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
    ]
